import { User, Company, Project, Task, TeamMember, ActivityItem, HelpArticle, Integration } from '@/types';

export const mockUser: User = {
  id: 'user-1',
  name: 'Alex Johnson',
  email: 'alex@flowboard.io',
  role: 'admin',
  createdAt: '2024-01-15T10:00:00Z',
  plan: 'pro',
  trialEndAt: '2024-02-15T10:00:00Z',
  jobRole: 'product_manager',
  teamSize: '6-20',
  region: 'US',
  title: 'Product Lead',
  timezone: 'America/New_York',
  emailNotifications: true,
  weeklySummary: true,
  theme: 'light',
  onboardingCompleted: true,
};

export const mockCompany: Company = {
  id: 'company-1',
  name: 'Acme Corp',
  size: '21-100',
  industry: 'Technology',
  domain: 'acme.io',
  createdAt: '2024-01-10T10:00:00Z',
};

export const mockProjects: Project[] = [
  {
    id: 'project-1',
    companyId: 'company-1',
    name: 'Website Redesign',
    description: 'Complete overhaul of the marketing website with new branding.',
    status: 'active',
    ownerId: 'user-1',
    ownerName: 'Alex Johnson',
    createdAt: '2024-01-20T10:00:00Z',
    startDate: '2024-02-01T00:00:00Z',
    priority: 'high',
    tasksCompleted: 8,
    totalTasks: 12,
  },
  {
    id: 'project-2',
    companyId: 'company-1',
    name: 'Mobile App v2',
    description: 'New features and performance improvements for the mobile application.',
    status: 'active',
    ownerId: 'user-2',
    ownerName: 'Sarah Chen',
    createdAt: '2024-01-25T10:00:00Z',
    startDate: '2024-02-15T00:00:00Z',
    priority: 'medium',
    tasksCompleted: 3,
    totalTasks: 10,
  },
  {
    id: 'project-3',
    companyId: 'company-1',
    name: 'API Documentation',
    description: 'Comprehensive API docs for developer partners.',
    status: 'paused',
    ownerId: 'user-3',
    ownerName: 'Mike Roberts',
    createdAt: '2024-01-18T10:00:00Z',
    startDate: '2024-03-01T00:00:00Z',
    priority: 'low',
    tasksCompleted: 2,
    totalTasks: 5,
  },
  {
    id: 'project-4',
    companyId: 'company-1',
    name: 'Q1 Marketing Campaign',
    description: 'Launch campaign for Q1 product updates.',
    status: 'archived',
    ownerId: 'user-1',
    ownerName: 'Alex Johnson',
    createdAt: '2023-12-15T10:00:00Z',
    startDate: '2024-01-01T00:00:00Z',
    priority: 'high',
    tasksCompleted: 15,
    totalTasks: 15,
  },
];

export const mockTasks: Task[] = [
  {
    id: 'task-1',
    projectId: 'project-1',
    title: 'Design new homepage mockups',
    description: 'Create 3 design variations for the new homepage.',
    status: 'done',
    assigneeId: 'user-2',
    assigneeName: 'Sarah Chen',
    completedAt: '2024-02-05T15:00:00Z',
    createdAt: '2024-01-22T10:00:00Z',
  },
  {
    id: 'task-2',
    projectId: 'project-1',
    title: 'Implement responsive navigation',
    description: 'Build mobile-first responsive navigation component.',
    status: 'in_progress',
    assigneeId: 'user-3',
    assigneeName: 'Mike Roberts',
    completedAt: null,
    createdAt: '2024-01-23T10:00:00Z',
  },
  {
    id: 'task-3',
    projectId: 'project-1',
    title: 'Set up analytics tracking',
    description: 'Integrate Google Analytics and Mixpanel.',
    status: 'backlog',
    assigneeId: null,
    assigneeName: undefined,
    completedAt: null,
    createdAt: '2024-01-24T10:00:00Z',
  },
  {
    id: 'task-4',
    projectId: 'project-1',
    title: 'Write content for About page',
    description: 'Draft copy for the new About Us section.',
    status: 'in_progress',
    assigneeId: 'user-1',
    assigneeName: 'Alex Johnson',
    completedAt: null,
    createdAt: '2024-01-25T10:00:00Z',
  },
];

export const mockTeamMembers: TeamMember[] = [
  {
    id: 'tm-1',
    userId: 'user-1',
    companyId: 'company-1',
    name: 'Alex Johnson',
    email: 'alex@flowboard.io',
    role: 'admin',
    status: 'active',
    joinedAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 'tm-2',
    userId: 'user-2',
    companyId: 'company-1',
    name: 'Sarah Chen',
    email: 'sarah@flowboard.io',
    role: 'member',
    status: 'active',
    joinedAt: '2024-01-20T10:00:00Z',
  },
  {
    id: 'tm-3',
    userId: 'user-3',
    companyId: 'company-1',
    name: 'Mike Roberts',
    email: 'mike@flowboard.io',
    role: 'member',
    status: 'active',
    joinedAt: '2024-01-22T10:00:00Z',
  },
  {
    id: 'tm-4',
    userId: 'user-4',
    companyId: 'company-1',
    name: 'Emma Wilson',
    email: 'emma@flowboard.io',
    role: 'viewer',
    status: 'pending',
    joinedAt: '2024-02-01T10:00:00Z',
  },
];

export const mockActivities: ActivityItem[] = [
  {
    id: 'activity-1',
    projectId: 'project-1',
    userId: 'user-1',
    userName: 'Alex Johnson',
    action: 'created',
    description: 'created the project',
    createdAt: '2024-01-20T10:00:00Z',
  },
  {
    id: 'activity-2',
    projectId: 'project-1',
    userId: 'user-2',
    userName: 'Sarah Chen',
    action: 'completed',
    description: 'completed task "Design new homepage mockups"',
    createdAt: '2024-02-05T15:00:00Z',
  },
  {
    id: 'activity-3',
    projectId: 'project-1',
    userId: 'user-3',
    userName: 'Mike Roberts',
    action: 'started',
    description: 'started working on "Implement responsive navigation"',
    createdAt: '2024-02-06T09:00:00Z',
  },
  {
    id: 'activity-4',
    projectId: 'project-1',
    userId: 'user-1',
    userName: 'Alex Johnson',
    action: 'added',
    description: 'added 2 new tasks',
    createdAt: '2024-02-07T11:00:00Z',
  },
];

export const mockHelpArticles: HelpArticle[] = [
  {
    id: 'article-1',
    title: 'How to create a project',
    content: 'Projects are the foundation of Flowboard. To create a new project, click the "New Project" button on the Projects page. Fill in the project name, description, and set the priority level. You can also assign an owner and set a start date.',
    category: 'Getting Started',
  },
  {
    id: 'article-2',
    title: 'How to invite teammates',
    content: 'Collaboration is key! Navigate to Settings > Team to invite new members. Click "Invite Teammate", enter their email address, select their role (Admin, Member, or Viewer), and optionally add a personal message. They will receive an invitation email.',
    category: 'Team Management',
  },
  {
    id: 'article-3',
    title: 'Understanding billing & plans',
    content: 'Flowboard offers three plans: Free, Pro, and Enterprise. The Free plan includes basic features for small teams. Pro unlocks advanced analytics, unlimited projects, and priority support. Enterprise adds SSO, dedicated support, and custom integrations.',
    category: 'Billing',
  },
  {
    id: 'article-4',
    title: 'Managing tasks effectively',
    content: 'Tasks help you break down projects into manageable pieces. Each task can have a status (Backlog, In Progress, Done), assignee, and description. Use the task list view to quickly update statuses and reassign work.',
    category: 'Projects',
  },
  {
    id: 'article-5',
    title: 'Setting up integrations',
    content: 'Connect Flowboard with your favorite tools. Go to Settings > Integrations to enable connections with Slack, HubSpot, Intercom, and Segment. Each integration can be configured with custom settings.',
    category: 'Integrations',
  },
];

export const mockIntegrations: Integration[] = [
  {
    id: 'int-slack',
    name: 'Slack',
    description: 'Get notifications and updates in Slack channels.',
    enabled: true,
    icon: 'slack',
  },
  {
    id: 'int-hubspot',
    name: 'HubSpot',
    description: 'Sync contacts and deals with HubSpot CRM.',
    enabled: false,
    icon: 'hubspot',
  },
  {
    id: 'int-intercom',
    name: 'Intercom',
    description: 'Connect customer conversations with projects.',
    enabled: true,
    icon: 'intercom',
  },
  {
    id: 'int-segment',
    name: 'Segment',
    description: 'Send events and user data to Segment.',
    enabled: false,
    icon: 'segment',
  },
];
